Repository gjohansson-ST/sector, pull requests merged in 2024-11, with the labels that each got.

#181 Overhaul of API
  custom_components/sector/__init__.py
  custom_components/sector/alarm_control_panel.py
  custom_components/sector/binary_sensor.py
  custom_components/sector/camera.py
  custom_components/sector/client.py
  custom_components/sector/config_flow.py
  custom_components/sector/const.py
  custom_components/sector/coordinator.py
  custom_components/sector/diagnostics.py
  custom_components/sector/endpoints.py
  custom_components/sector/lock.py
  custom_components/sector/manifest.json
  custom_components/sector/sensor.py
  custom_components/sector/switch.py
Labels: enhancement

#183 Various cleanup
  .pylintrc
  api-info/api_info.py
  custom_components/sector/__init__.py
  custom_components/sector/alarm_control_panel.py
  custom_components/sector/binary_sensor.py
  custom_components/sector/camera.py
  custom_components/sector/client.py
  custom_components/sector/config_flow.py
  custom_components/sector/const.py
  custom_components/sector/coordinator.py
  custom_components/sector/diagnostics.py
  custom_components/sector/endpoints.py
  custom_components/sector/lock.py
  custom_components/sector/manifest.json
  custom_components/sector/sensor.py
  custom_components/sector/strings.json
  custom_components/sector/switch.py
  custom_components/sector/translations/en.json
  custom_components/sector/translations/fr.json
  custom_components/sector/translations/no.json
Labels: refactor

#184 Fixa svenska
  custom_components/sector/translations/se.json
Labels: bugfix

#185 Remove api.md
  api-info/api.md
Labels: refactor

#186 Mod config flow
  custom_components/sector/config_flow.py
Labels: refactor

#188 Base entity
  custom_components/sector/alarm_control_panel.py
  custom_components/sector/binary_sensor.py
  custom_components/sector/camera.py
  custom_components/sector/entity.py
  custom_components/sector/lock.py
  custom_components/sector/sensor.py
  custom_components/sector/switch.py
Labels: refactor

#189 Add feature request
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#203 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#207 Restore previous diagnostics
  custom_components/sector/diagnostics.py
Labels: new-feature

#206 bug-fix: entry.py debug error
  custom_components/sector/entity.py
Labels: bugfix

#204 enhancement: 202-remove-panel_id-get-from-api
  custom_components/sector/client.py
  custom_components/sector/config_flow.py
  custom_components/sector/coordinator.py
Labels: enhancement

#210 209 partial alarm not implemented
  custom_components/sector/client.py
  custom_components/sector/endpoints.py
Labels: bugfix

#208 191 remove panel code
  custom_components/sector/alarm_control_panel.py
  custom_components/sector/client.py
  custom_components/sector/config_flow.py
  custom_components/sector/const.py
  custom_components/sector/coordinator.py
  custom_components/sector/diagnostics.py
  custom_components/sector/entity.py
  custom_components/sector/lock.py
Labels: new-feature

#211 Fix alarm state
  custom_components/sector/alarm_control_panel.py
Labels: bugfix

#212 Fix config flow
  custom_components/sector/client.py
  custom_components/sector/config_flow.py
  custom_components/sector/const.py
  custom_components/sector/translations/en.json
  custom_components/sector/translations/se.json
Labels: enhancement

#224 fix: 199: Update to new AlarmState enum
  custom_components/sector/alarm_control_panel.py
  hacs.json
  readme.md
Labels: enhancement

#226 Use SelectOptionDict in config flow
  custom_components/sector/config_flow.py
Labels: enhancement

#227 Various small fixes
  custom_components/sector/alarm_control_panel.py
  custom_components/sector/binary_sensor.py
  custom_components/sector/camera.py
  custom_components/sector/coordinator.py
  custom_components/sector/entity.py
  custom_components/sector/event.py
  custom_components/sector/lock.py
  custom_components/sector/manifest.json
  custom_components/sector/sensor.py
Labels: enhancement

#228 Improve naming and binary sensor entity description
  custom_components/sector/alarm_control_panel.py
  custom_components/sector/binary_sensor.py
  custom_components/sector/camera.py
  custom_components/sector/coordinator.py
  custom_components/sector/entity.py
  custom_components/sector/lock.py
  custom_components/sector/sensor.py
  custom_components/sector/switch.py
Labels: enhancement

#229 Don't refresh on platform add
  custom_components/sector/binary_sensor.py
  custom_components/sector/event.py
  custom_components/sector/sensor.py
Labels: enhancement

#231 Clean up platform loads
  custom_components/sector/alarm_control_panel.py
  custom_components/sector/binary_sensor.py
  custom_components/sector/camera.py
  custom_components/sector/event.py
  custom_components/sector/lock.py
  custom_components/sector/sensor.py
  custom_components/sector/switch.py
Labels: enhancement

#232 Add model to sector
  custom_components/sector/model.py
Labels: enhancement

#233 Add smartplugs to action endpoints
  custom_components/sector/client.py
  custom_components/sector/endpoints.py
Labels: enhancement

#234 Add migration to not handle migration
  custom_components/sector/__init__.py
  custom_components/sector/config_flow.py
  custom_components/sector/model.py
Labels: enhancement

#237 Fix mandatory entry data/options
  custom_components/sector/alarm_control_panel.py
  custom_components/sector/binary_sensor.py
  custom_components/sector/lock.py
Labels: enhancement

#238 Panel id is serial number for alarm
  custom_components/sector/alarm_control_panel.py
Labels: enhancement

#239 Fix mypy issues
  custom_components/sector/alarm_control_panel.py
  custom_components/sector/client.py
  custom_components/sector/config_flow.py
  custom_components/sector/coordinator.py
  custom_components/sector/lock.py
Labels: enhancement

#240 Fix modelling
  custom_components/sector/alarm_control_panel.py
  custom_components/sector/client.py
  custom_components/sector/config_flow.py
  custom_components/sector/coordinator.py
  custom_components/sector/lock.py
  custom_components/sector/model.py
Labels: enhancement

#241 Add redact info to diagnostics
  custom_components/sector/diagnostics.py
Labels: enhancement

#242 Fix entity names
  custom_components/sector/binary_sensor.py
  custom_components/sector/sensor.py
Labels: enhancement
